### ISSUE TITLE
Crash when deleting a receipt after minimizing the app with dialog opened 

### ISSUE THREAD

**Issue by thaissugeta** [munhra/IrishCofee#119]
Steps to reproduce:
- Open the app
- Go to Receipts
- Select one receipt and open it
- Press Delete button
- The delete dialog is showed
- Minimize the app with the dialog opened
- Open the app again
- Press OK button
- The app crashes

**Comment by munhra** [comment]
Solved in #130

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.3.2
