### ISSUE TITLE
Crash when you delete a receipt if you cancel previously

### ISSUE THREAD

**Issue by thaissugeta** [munhra/IrishCofee#121]
Steps to reproduce:
- Open the app
- Go to Receipts
- Select one receipt and open it
- Press Delete button
- The delete dialog is showed
- Press Cancel button
- Press Delete button again
- The delete dialog is showed
- Press OK
- The app crashes

**Comment by munhra** [comment]
Solved in #129

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.3.2
