### ISSUE TITLE
Crash using app with 3G

### ISSUE THREAD

**Issue by thaissugeta** [munhra/IrishCofee#141]
Steps to reproduce:
- Insert a sim card with 3G connection
- Open the app
- Select itens and navigate through the app 
- Go to receipts, back to menu, go to checkout, select cafe tab and change to lunch. Do this step many times sometimes the app crashes

**Comment by munhra** [comment]
[CrashLog.txt](https://github.com/munhra/IrishCofee/files/415158/CrashLog.txt)

**Comment by munhra** [comment]
For sure the problem here is with the line 
'''
private var selectedCategory: String? {
        let control = contentView.categoryControl
        return control.titleForSegmentAtIndex(control.selectedSegmentIndex)
    }
'''

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.3.2
