### ISSUE TITLE
If you do a payment after the PIN code was reseted a toast is showed in the receipt screen: "String.PaymentStrings.orderConflict"

### ISSUE THREAD

**Issue by thaissugeta** [munhra/IrishCofee#143]
Steps to reproduce:

- Insert 2 credit cards
- Buy one item using one credit card
- Buy other item using the other credit card
- Go to menu and select one item
- Proceed
- Select one credit card
- Insert wrong PIN code 3 times
- The PIN is reset and credit cards should be inserted again
- Add new credit card
- Insert a PIN code
- Add new credit card
- Do a payment using the credit card
- Verify that in the receipt screen a toast is showed:  "String.PaymentStrings.orderConflict"
See the attached screen.
![dsc_0003](https://cloud.githubusercontent.com/assets/20931397/17589157/796c1f3c-5fa9-11e6-8c9c-f4143de05cc6.JPG)

**Comment by silvanosouzajunior** [comment]
Solved with another Bug Fix

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.3.0
