### ISSUE TITLE
Receipts readable from distance

### ISSUE THREAD

**Issue by munhra** [munhra/IrishCofee#165]
When we tested the Android app in live environment the Baristas feedbacked that the time and date of the receipts are too hard to read.

We changed places of restaurant and timestamp and increased font size to improve it. We should do the same on iOS.

See Android version for details.

**Comment by munhra** [comment]
![img_0047](https://cloud.githubusercontent.com/assets/7031566/17664209/e7b9cd28-62c8-11e6-971e-91b0def8baba.JPG)

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.3.2
