### ISSUE TITLE
Crash when using application

### ISSUE THREAD

**Issue by munhra** [munhra/IrishCofee#180]
Crash was found during application use 

- Using 3G environment
- Add two credit cards
- Do payments using one credit card
- Do payments now using the other credit card
- Reset the PIn code
- Add one credit card again and register a different Pin code
- Tap at back button in all screens that it is available until app crashes

**Comment by munhra** [comment]
[caffinho-iOS  15-08-16 17.txt](https://github.com/munhra/IrishCofee/files/420397/caffinho-iOS.15-08-16.17.txt)

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.5.0
