### ISSUE TITLE
List all strings that are not translated in android

### ISSUE THREAD

**Issue by munhra** [munhra/IrishCofee#191]

**Comment by silvanosouzajunior** [comment]
Seguem as Strings que faltam traduzir para Dinamarquês:
​
Use your google account to login
Authentication Failed
Welcome
Authenticating
Delete receipt
Are you sure?
Delete all receipts
Proceed
We couldn't connect to the server
Please check your connection
Internal aplication server error
Application server error
Retry
Validating PIN
Card removed from the list
The order price exceeds the limit. 
Proceed to checkout before add more items to the order
Remove some items before proceeds to Checkout
Pin was registered successfully
Pin could not be registered.​
