### ISSUE TITLE
When minimizing app with dialog "Open in Caffinho" after opening again the dialog is closed

### ISSUE THREAD

**Issue by thaissugeta** [munhra/IrishCofee#199]
Steps to reproduce:
- Open and login
- Add a new credit card
- A dialog "Open in Caffinho" is showed
- Minimize the app
- Open the app again
- The dialog was closed. The dialog should not be closed.

**Comment by munhra** [comment]
This dialog is under safari control, it is not possible to keep it open as safari will lose it's session and caffinho application is not informed. So this bug will not be fixed.
