### ISSUE TITLE
Incorrect label when entering wrong pin code

### ISSUE THREAD

**Issue by munhra** [munhra/IrishCofee#92]
Fix the following message
![captura de tela 2016-08-04 as 08 02 15](https://cloud.githubusercontent.com/assets/7031566/17399664/cbb9fb8c-5a19-11e6-83ba-457ce188ebfa.png)

the message should be "Incorrect PIN. 2 tries left

**Comment by munhra** [comment]
Done but it need to test

**Comment by thaissugeta** [comment]
Test OK - Verified on version 0.2.0
